### ISSUE TITLE
go 1.16 compilation problem

### ISSUE THREAD

**Issue by SekiBetu** [nnn-revo2012/livedl#1]
![image](https://user-images.githubusercontent.com/38283893/109118826-cafb8d00-777e-11eb-9942-ec34f65f0164.png)

go version is 1.16

it says package not found

**Comment by SekiBetu** [comment]
`GO111MODULE=off go build src/livedl.go`

**Comment by nnn-revo2012** [comment]
```
/root/go/src/golang.org/x/crypto/sha3 (from $GOPATH)
```
Add .bashrc `export GOPATH=/home/livedl`   
(or your livedl compile home path)

**Comment by SekiBetu** [comment]
> ```
> /root/go/src/golang.org/x/crypto/sha3 (from $GOPATH)
> ```
> 
> Add .bashrc or .bash_profile on your livedl compile home path and go get .
> This will install the source files in $GOPATH/src/golang.org/x/crypto/sha3 etc.
> 
> ```
> export GOPATH=/home/livedl        ( Or your livedl compile home path)
> export GO111MODULE=off
> source ~/.bashrc     (Or .bash_profile)
> go get github.com/gorilla/websocket
> go get golang.org/x/crypto/sha3
> go get github.com/mattn/go-sqlite3
> go get github.com/gin-gonic/gin
> ```

thanks for your reply, i tried to set the GOPATH to livedl path, but still can't compile, it says:

```shell
sekibetu@debian:~/livedl$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sekibetu/.cache/go-build"
GOENV="/home/sekibetu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sekibetu/livedl/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sekibetu/livedl/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2917465768=/tmp/go-build -gno-record-gcc-switches"
sekibetu@debian:~/livedl$ ls -al
total 72
drwxr-xr-x  5 sekibetu sekibetu 4096 Feb 26 01:39 .
drwxr-xr-x  6 sekibetu sekibetu 4096 Feb 26 01:35 ..
-rw-r--r--  1 sekibetu sekibetu  108 Feb 26 01:31 build-386.ps1
-rw-r--r--  1 sekibetu sekibetu 1142 Feb 26 01:31 build.ps1
-rw-r--r--  1 sekibetu sekibetu 6864 Feb 26 01:31 changelog.txt
-rw-r--r--  1 sekibetu sekibetu  544 Feb 26 01:31 Dockerfile
drwxr-xr-x  8 sekibetu sekibetu 4096 Feb 26 01:31 .git
-rw-r--r--  1 sekibetu sekibetu  247 Feb 26 01:31 .gitignore
-rw-r--r--  1 sekibetu sekibetu 1068 Feb 26 01:31 LICENSE
-rw-r--r--  1 sekibetu sekibetu 1353 Feb 26 01:31 livedl-logger.go
drwxr-xr-x  3 sekibetu sekibetu 4096 Feb 26 01:35 pkg
-rw-r--r--  1 sekibetu sekibetu  486 Feb 26 01:31 readme-gen.pl
-rw-r--r--  1 sekibetu sekibetu 7009 Feb 26 01:31 README.md
-rw-r--r--  1 sekibetu sekibetu  931 Feb 26 01:31 replacelocal.pl
drwxr-xr-x 24 sekibetu sekibetu 4096 Feb 26 01:36 src
-rw-r--r--  1 sekibetu sekibetu 1066 Feb 26 01:31 updatebuildno.go
sekibetu@debian:~/livedl$ go build src/livedl.go 
unexpected directory layout:
        import path: _/home/sekibetu/livedl/src/buildno
        root: /home/sekibetu/livedl/src
        dir: /home/sekibetu/livedl/src/buildno
        expand root: /home/sekibetu/livedl/
        expand dir: /home/sekibetu/livedl/src/buildno
        separator: /
sekibetu@debian:~/livedl$ 
```

**Comment by nnn-revo2012** [comment]
I was able to compile successfully with golang 1.16 on my computer (Windows 10).
However, if you can't compile in your environment, golang 1.15 is better.
Or you may be able to get rid of all the files in livedl and then start over with `go get ...'.

module-aware mode:
1.You make a mod with go init mod livedl in *livedl / src*
2.All the relative paths of `import` in the livedl sources to livedl / ...
eg `import "../options" ->  "livedl/options"`
3.compile: `cd src    go build livedl.go`

**Comment by nnn-revo2012** [comment]
If you really want to try module-aware mode, use the git branch below.  
This is TEST VERSION:
```
git clone -b git module https://github.com/nnn-revo2012/livedl.git
git checkout module
```

Compile:
```
cd src
go build -o ../livedl livedl.go
```

**Comment by SekiBetu** [comment]
> If you really want to try module-aware mode, use the git branch below.
> This is TEST VERSION:
> 
> ```
> git clone -b module https://github.com/nnn-revo2012/livedl.git
> git checkout module
> ```
> 
> Compile:
> 
> ```
> cd src
> go build -o ../livedl livedl.go
> ```

omg, thanks a lot, you are so kind, it works like a charm!
