### ISSUE TITLE
Get https://live2.nicovideo.jp/watch/lvxxxxxxxxx: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Kotsuha** [nnn-revo2012/livedl#2]
Thank you for your livedl builds. It helped me so many times. I just encountered a Timeshift which I cannot download. I try to download another Timeshift and it's working. I don't know what's different in this one. I notice the Nico message is different:

タイムシフト予約リスト

no | name | status | delete
--- | --- | --- | ---
9 | みせられないよ9 | <button>視聴する</button> 購入者向け映像視聴期限:[2021/03/14(日) 23:59まで] | [削除]
10 | みせられないよ10 | <button>視聴する</button> 期限中、何度でも視聴できます [2021/03/05(金)23:59まで] | [削除]
11 | みせられないよ11 | <button>視聴する</button> 期限中、何度でも視聴できます [2021/03/20(土)23:59まで] | [削除]
12 | みせられないよ12 | <button>視聴する</button> [2021/03/28(日)23:59まで] | [削除]

I cannot download # 9. The message "購入者向け映像視聴期限" is different from others. Don't know if this provide any clues.

Below is my commands:

```
F:\Rec\lvxxxxxxxxx - みせられないよ\livedl
$ livedl.x86 -nico-login "みせられないよ,みせられないよ" lvxxxxxxxxx -nico-login-only=on
niconico account saved.
Conf(NicoLoginOnly): true
Conf(NicoFormat): ""
Conf(NicoLimitBw): 0
Conf(NicoHlsOnly): false
Conf(NicoRtmpOnly): false
Conf(NicoFastTs): false
Conf(NicoAutoConvert): false
Conf(NicoForceResv): false
Conf(NicoSkipHb): false
Conf(HttpSkipVerify): false
Conf(HttpTimeout): 5
chdir: F:\Rec\lvxxxxxxxxx - みせられないよ\livedl
Get https://live2.nicovideo.jp/watch/lvxxxxxxxxx: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This is my version ↓↓ which is built from 20210202.47a (47ef12c1616bb1ba850a75fe4d75e6168da431d6)

```
$ livedl.x86 --version
livedl (20210228.48-windows-386)
```

**Comment by nnn-revo2012** [comment]
Please tell me the broadcast ID (lvxxxxxxxx) of "みせられないよ9".
Otherwise I can't look at anything.

**Comment by Kotsuha** [comment]
It's lv330236283. But I just tried it and it's working now :)
Maybe I need to wait a little after the live ends.
